# Site settings
title: Kwarf's Blog
description: My personal blog about programming, R/C, UAV, FPV and other geeky things.
baseurl: ""
url: "http://blog.kwarf.com"

full_name: Jimmy 'Kwarf' Bergström
twitter_username: TheKwarf
github_username: Kwarf

gems: ['jekyll-paginate']
paginate: 3

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
exclude: [vendor, Gemfile]
sass:
    style: compressed
